name: kalidocs

services:
  api:
    build: ../server
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    deploy:
      replicas: 4
    networks:
      - internal
    volumes:
      - ../server:/app
      - ../server/.env.production:/app/.env
      - ../server/static:/app/static
      - ../server/media:/app/media
    depends_on:
      - db

  celery:
    container_name: celery
    build: ../server
    command: celery -A core worker -l info
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ../server:/app
      - ../server/.env.production:/app/.env
      - ../server/static:/app/static
      - ../server/media:/app/media
    depends_on:
      - db
      - redis
      - api

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ../server/.env.production
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:alpine
    command: sh -c "redis-server --save 20 1 --loglevel warning --appendonly yes --requirepass $$REDIS_PASSWORD"
    restart: unless-stopped
    ports:
      - 6379
    env_file:
      - ../server/.env.production
    networks:
      - internal
    volumes:
      - redis_data:/data

  nginx:
    container_name: nginx
    build:
      context: ..
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - internal
    volumes:
      - ../nginx/nginx.production.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/nginx.cors.conf:/etc/nginx/cors.conf
      - ../server/static:/app/static
      - ../server/media:/app/media
    depends_on:
      - api

networks:
  internal:

volumes:
  postgres_data:
  redis_data:
